apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bankapp
  template:
    metadata:
      labels:
        app: bankapp
    spec:
      containers:
        - name: bankapp
          image: pratikgharde12/bankapp:Release-1.0.11
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_DATABASE
              value: bankappdb
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bankapp-secrets
                  key: MYSQL_PASSWORD
            - name: OLLAMA_URL
              value: "http://ollama:11434"
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15              
---
apiVersion: v1
kind: Service
metadata:
  name: bankapp
spec:
  selector:
    app: bankapp
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort
